export type ThemeTypes = {
    name: string;
    dark: boolean;
    variables?: object;
    colors: {
        primary?: string;
        secondary?: string;
        info?: string;
        orange?: string;
        success?: string;
        warning?: string;
        error?: string;
        indigo?: string;
        lightprimary?: string;
        lightsecondary?: string;
        lightsuccess?: string;
        lighterror?: string;
        lightinfo?: string;
        lightwarning?: string;
        lightindigo?: string;
        textPrimary?: string;
        textSecondary?: string;
        borderColor?: string;
        hoverColor?: string;
        inputBorder?: string;
        containerBg?: string;
        background?: string;
        surface?: string;
        grey100?: string;
        grey200?: string;
        darkbg?:string;
        bglight?:string;
        bgdark?:string;
        pink?:string;
        primary1?:string;
        primary5?:string;
        grey1?:string;
        grey4?:string;
        success1?:string;
        success5?:string;
        info1?:string;
        info5?:string;
        orange1?:string;
        orange5?:string;
        indigo1?:string;
        indigo5?:string;
        amber1?:string;
        amber5?:string;
        lime1?:string;
        lime5?:string;
        teal1?:string;
        teal5?:string;
        pink1?:string;
        pink5?:string;
    };
};
