export type TAdvancedFilterCriteria = {
  all_params: string;
  campaign: string;
  agent_phone: string[];
  creator: string[];
  create_time_period: number[];
  assignment_date: number[];
  first_communication: number[];
  last_duty_date: number[];
  last_done_duty_date: number[];
  first_done_duty_date: number[];
  next_follow_up_timestamp: number[];
  last_contact_at_timestamp_period: number[];
  media_name: string[];
  department: string[];
  status: string[];
  priority: string[];
  page: number;
  page_size: number;
  result_of_last_contact: string[];
  agent_name: string;
  lead_name: string;
};

export type TAugmentedFilterCriteria = TAdvancedFilterCriteria & {
  campaign: string;
  create_time_period_start: string;
  create_time_period_end: string;
  assignment_date_start: string;
  assignment_date_end: string;
  first_communication_start: string;
  first_communication_end: string;
  last_duty_date_start: string;
  last_duty_date_end: string;
  last_done_duty_date_start: string;
  last_done_duty_date_end: string;
  first_done_duty_date_start: string;
  first_done_duty_date_end: string;
  next_follow_up_timestamp_start: string;
  next_follow_up_timestamp_end: string;
  last_contact_at_timestamp_period_start: string;
  last_contact_at_timestamp_period_end: string;
};
